# Generated by Django 2.2.3 on 2019-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Roll', models.IntegerField()),
                ('Registration', models.IntegerField()),
                ('Father_name', models.CharField(max_length=120)),
                ('Mother_name', models.CharField(max_length=120)),
            ],
        ),
    ]
