# Generated by Django 2.1.5 on 2019-08-29 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Image',
            field=models.ImageField(default=datetime.datetime(2019, 8, 29, 18, 19, 11, 462412, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
