# Generated by Django 2.1.5 on 2019-08-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Image',
            field=models.FileField(upload_to=''),
        ),
    ]
