# Generated by Django 2.1.5 on 2019-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190923_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
