# Generated by Django 2.1.5 on 2019-09-25 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1st', 'FirstShift'), ('2nd', 'SecondShift')], max_length=1)),
                ('Date', models.DateField(blank=True, null=True)),
                ('In_Time', models.TimeField(default=django.utils.timezone.now)),
                ('Out_Time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
