# Generated by Django 2.1.5 on 2019-09-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('1st', 'FirstShift'), ('2nd', 'SecondShift')], max_length=3),
        ),
    ]
